"""Data models for code generation and review."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class CodeLanguage(str, Enum):
    PYTHON = "python"
    TYPESCRIPT = "typescript"
    JAVASCRIPT = "javascript"


class CodeFile(BaseModel):
    """A single generated source file."""
    path: str = Field(description="Relative file path, e.g. 'src/main.py'")
    content: str = Field(description="Complete file contents")
    language: CodeLanguage
    description: str = Field(description="What this file does")


class Prototype(BaseModel):
    """A complete code prototype generated by the Developer agent."""
    id: str = Field(default_factory=lambda: f"PROTO-{uuid4().hex[:8].upper()}")
    product_name: str
    files: list[CodeFile] = Field(min_length=1)
    entry_point: str = Field(description="How to run this — e.g. 'python src/main.py'")
    setup_instructions: str = Field(default="No special setup required", description="Dependencies and setup steps")
    readme: str = Field(description="README content explaining the prototype")
    confidence: float = Field(ge=0.0, le=1.0, default=0.7)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_lines(self) -> int:
        return sum(len(f.content.splitlines()) for f in self.files)


class ReviewVerdict(str, Enum):
    APPROVED = "approved"
    CHANGES_REQUESTED = "changes_requested"
    REJECTED = "rejected"


class CodeReview(BaseModel):
    """Structured code review from the Architect."""
    prototype_id: str
    verdict: ReviewVerdict
    issues: list[str] = Field(description="Specific problems found")
    strengths: list[str] = Field(description="What's done well")
    suggestions: list[str] = Field(description="Improvements for the next iteration")
    clean_code_score: int = Field(ge=1, le=10)
    security_score: int = Field(ge=1, le=10)
    architecture_score: int = Field(ge=1, le=10)
    overall_score: int = Field(ge=1, le=10)
    reasoning: str
