"""Data models for product ideas and related concepts."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class IdeaStatus(str, Enum):
    """Lifecycle status of a product idea."""

    DRAFT = "draft"
    EVALUATING = "evaluating"
    PASSED = "passed"
    FAILED = "failed"
    ARCHIVED = "archived"


class ProductIdea(BaseModel):
    """A single product idea generated by the Visionary agent."""

    id: str = Field(default_factory=lambda: uuid4().hex[:12])
    name: str = Field(description="Short, memorable product name")
    elevator_pitch: str = Field(description="One-paragraph description of what it does and why")
    target_audience: str = Field(description="Who is this for?")
    value_proposition: str = Field(description="What's the core benefit?")
    problem_statement: str = Field(description="What pain point does this solve?")
    confidence: float = Field(
        ge=0.0, le=1.0, description="Agent's confidence in this idea (0.0–1.0)"
    )
    status: IdeaStatus = IdeaStatus.DRAFT
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class IdeaBatch(BaseModel):
    """A batch of ideas produced in one ideation round."""

    session_id: str = Field(default_factory=lambda: uuid4().hex[:8])
    ideas: list[ProductIdea] = Field(min_length=1)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    prompt_used: str = ""
