"""Data models for Product Requirements Documents generated by the PM Agent."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class Priority(str, Enum):
    """MoSCoW prioritisation."""
    MUST = "must_have"
    SHOULD = "should_have"
    COULD = "could_have"
    WONT = "wont_have"


class UserStory(BaseModel):
    """A single user story with acceptance criteria."""
    id: str = Field(default_factory=lambda: f"US-{uuid4().hex[:6].upper()}")
    persona: str = Field(description="As a [type of user]")
    action: str = Field(description="I want to [action]")
    benefit: str = Field(description="So that [benefit]")
    acceptance_criteria: list[str] = Field(
        min_length=1,
        description="Testable criteria that define 'done'"
    )
    priority: Priority = Priority.MUST
    estimated_complexity: str = Field(
        description="Low / Medium / High",
        default="Medium"
    )


class FeatureSpec(BaseModel):
    """A feature in the product roadmap."""
    name: str
    description: str
    user_stories: list[UserStory] = Field(min_length=1)
    priority: Priority
    dependencies: list[str] = Field(
        default_factory=list,
        description="Other features this depends on"
    )
    technical_notes: str = Field(
        default="",
        description="Implementation guidance from the Architect"
    )


class ProductPRD(BaseModel):
    """Full Product Requirements Document generated by the PM Agent."""
    id: str = Field(default_factory=lambda: f"PRD-{uuid4().hex[:8].upper()}")
    product_name: str
    version: str = "0.1.0"

    problem_statement: str = Field(description="The core problem being solved")
    vision: str = Field(description="What does success look like?")
    target_audience: str = Field(description="Primary users and their context")

    in_scope: list[str] = Field(description="What's included in v1")
    out_of_scope: list[str] = Field(description="Explicitly excluded from v1")

    features: list[FeatureSpec] = Field(min_length=1)

    suggested_tech_stack: str = Field(description="Recommended technologies")
    data_model_overview: str = Field(description="Key entities and relationships")
    api_overview: str = Field(
        default="",
        description="Main API endpoints or interfaces"
    )

    performance_requirements: str = Field(default="")
    security_requirements: str = Field(default="")

    open_questions: list[str] = Field(
        default_factory=list,
        description="Unresolved questions that need answers"
    )
    confidence: float = Field(ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_user_stories(self) -> int:
        return sum(len(f.user_stories) for f in self.features)

    @property
    def must_have_count(self) -> int:
        return sum(
            1 for f in self.features
            for us in f.user_stories
            if us.priority == Priority.MUST
        )
